# Generated by Django 4.2.7 on 2023-11-23 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_alter_task_assignees_alter_task_is_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("deadline", "is_completed", "priority")},
        ),
    ]
