# Generated by Django 4.2.7 on 2023-11-23 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_completed", "-priority")},
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
