# Generated by Django 4.2.7 on 2023-11-23 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_alter_task_options_alter_task_assignees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
